name: Deploy Static Frontend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-files
          path: ./public

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-files
          path: public

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: smart-daily-dashboard-app
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./public